server:
  port: 8080
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/girls?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: root


